#       ___    ___ ________  ________  ________
#      |\  \  /  /|\   __  \|\   __  \|\   ___ \
#      \ \  \/  / | \  \|\  \ \  \|\  \ \  \_|\ \
#       \ \    / / \ \   ____\ \   __  \ \  \ \\ \
#        /     \/   \ \  \___|\ \  \ \  \ \  \_\\ \
#       /  /\   \    \ \__\    \ \__\ \__\ \_______\
#      /__/ /\ __\    \|__|     \|__|\|__|\|_______|
#     |__|/  \|__|        by EnttbotX

# Donate Me! im poor :(
# ko-fi.com/enttbotx

# My web page - Wiki can be found here:
# enttbotx.github.io

# don´t touch this ⬇️
config-version: 1.4.0

update-log:
  enabled: true
  permission: "xpad.updater"

pads:
  '1': # <- pad ID
    speed: 5
    direction: player-view
    launch-plate: STONE_PRESSURE_PLATE
    bottom-block: REDSTONE_BLOCK # ANY // BLOCK_NAME
    sound: ENTITY_FIREWORK_ROCKET_LAUNCH
    cooldown: 2 # <- It applies to the player who used it, not all players.
    permission: "xpad.use.1" # permission to use the pad
    actions: # made when use a pad
      send-message:
        enabled: false
        message:
          - "&3Launched!"

      send-title:
        enabled: false
        title: "&cLaunched"
        subtitle: "&fbye-bye"

        in: 10
        stay: 5
        out: 10

      execute-cmd:
        enabled: false
        execute:
          - "eco give %player% 100"
    trail:
      enabled: true
      type: "FLAME" # particle
  '2':
    speed: 12
    direction: single-direction
    vector: [20, 10] # yaw / pitch
    launch-plate: STONE_PRESSURE_PLATE
    bottom-block: ANY # ANY // BLOCK_NAME
    sound: ENTITY_FIREWORK_ROCKET_LAUNCH
    cooldown: 2
    permission: "xpad.use.2"
    actions: # made when use a pad
      send-message:
        enabled: false
        message:
          - "&3Launched!"

      send-title:
        enabled: false
        title: "&cLaunched"
        subtitle: "&fbye-bye"

        in: 10
        stay: 5
        out: 10

      execute-cmd:
        enabled: false
        execute:
          - "eco give %player% 100"
    trail:
      enabled: true
      type: "FLAME" # particle

world-list:
  enabled: true
  list-mode: "whitelist" # Whitelist / Blacklist
  worlds:
    - "world1"
    - "world2"