main: x.Entt.XPad.XP
version: 1.4.0
name: XPad
author: Enttbot
api-version: "1.13"
softdepend: [PlaceholderAPI]

commands:
  xpad:
    description: The main command of XP plugin.

permissions:
  xpad.*:
    description: Gives access to all permissions.
    children:
      xpad.launch: true
      xpad.op: true
  xpad.op:
    description: Permission only for use admin commands.
    default: op
  xpad.launch:
    description: Can they be launched
    default: true