main: x.Entt.XPad.XPad
version: 1.1.0
name: XPad
author: Enttbot
api-version: "1.13"

commands:
  xpad:
    description: The main command of XPad plugin.

permissions:
  xpad.*:
    description: Gives access to all permissions.
    children:
      rsl.launch: true
      rsl.commands: true
  xpad.launch:
    description: Can they be launched
    default: true
  xpad.commands:
    description: Can they reload the config
    default: op